export const COMMAND_MODULE_OPTIONS = "COMMAND_MODULE_OPTIONS";
export const COMMAND_MODULE_COMMANDER_DECORATOR = "COMMAND_MODULE_COMMANDER_DECORATOR";
export const COMMAND_MODULE_COMMAND_DECORATOR = "COMMAND_MODULE_COMMAND_DECORATOR";

export const COMMAND_MODULE_COMMAND_POSITIONAL_DECORATOR = "COMMAND_MODULE_COMMAND_POSITIONAL_DECORATOR";
export const COMMAND_MODULE_COMMAND_OPTION_DECORATOR = "COMMAND_MODULE_COMMAND_OPTION_DECORATOR";
